name = "nmsco-corvette-library"
main = "src/index.js"
compatibility_date = "2026-09-01"

[vars]
DISCORD_APPLICATION_ID = "1554537284173439106"
DISCORD_GUILD_ID = "285756001469202432"
APPROVAL_CHANNEL_ID = "1554536984255401994"
APPROVER_USER_ID = "80942727767785472"
GITHUB_OWNER = "TAZmd"
GITHUB_REPO = "nmsco-corvette-library"
TURNSTILE_SITE_KEY = "0x4AAAAAAFJ2-ulEDxzRxFIL"

[observability.logs]
enabled = true
invocation_logs = true
